version: '3.9'

services:  
  psql:
    container_name: martendb-demo-postgresql
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "demo-postgresql"
      POSTGRES_DB: postgres_demo_db
  adminer:
    container_name: martendb-demo-adminer
    image: adminer
    restart: always
    depends_on: 
      - psql
    ports:
      - 8081:8080
volumes:
  cache:
    driver: local